### ISSUE TITLE
Update the Profile README for the organization

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/.github#7]
### Feature details?

The current README is good enough & I made some subtle changes to it by adding more info like;

1. _What the community is & what does it stand for?_
2. _Where are the members of the community from?_
3. _How can one become a member of the community and/or server it?_

Feel free to take a look at the [modified example](https://gist.github.com/Jarmos-san/d34771c77754874397010b9b42332436).

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/developersIndia/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bhupesh-V** [comment]
In becoming the part of the community section, we have mentioned GOI, I don't think we should do that right now considering we have no accreditation whatsoever,
Let's remove that for now, apart from that, everything looks good, just need some paragraph separations

**Comment by Jarmos-san** [comment]
> ....I don't think we should do that right now considering we have no accreditation whatsoever.

Yeah totally makes sense, so +1 on that.

I'll prep a PR for this issue in a couple of days & send it for review then.
